# Generated by Django 2.2.17 on 2021-01-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('votes', models.IntegerField()),
                ('image', models.ImageField(upload_to='Images/')),
                ('body', models.CharField(max_length=200)),
            ],
        ),
    ]
