# Generated by Django 2.2.17 on 2021-01-17 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hunter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(default=None, upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='body',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
